namespace: community
name: windows
version: 0.2.0
readme: README.md
authors:
- Jordan Borean @jborean93
- Matt Davis @nitzmahone
description: |
  Ansible collection for community Windows pluigns.
license_file: COPYING
tags:
- windows
dependencies:
  ansible.windows: '>=0.0.0,<2.0.0'
repository: https://github.com/ansible-collections/community.windows
documentation: https://github.com/ansible-collections/community.windows/tree/main/docs
homepage: https://github.com/ansible-collections/community.windows
issues: https://github.com/ansible-collections/community.windows/issues
build_ignore:
- tests/integration/inventory*
- changelogs/.plugin-cache.yaml
