namespace: community
name: windows
version: 3.0.0
readme: README.md
authors:
  - Jordan Borean @jborean93
  - Matt Davis @nitzmahone
description: |
  Ansible collection for community Windows plugins.
license_file: COPYING
tags:
  - windows
dependencies:
  ansible.windows: ">=3.0.0,<4.0.0"
repository: https://github.com/ansible-collections/community.windows
documentation: https://docs.ansible.com/ansible/devel/collections/community/windows
homepage: https://github.com/ansible-collections/community.windows
issues: https://github.com/ansible-collections/community.windows/issues
build_ignore:
  - tests/integration/inventory*
  - changelogs/.plugin-cache.yaml
